// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface MenuListResVo
 */
export interface MenuListResVo {
    /**
     * 
     * @type {number}
     * @memberof MenuListResVo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof MenuListResVo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuListResVo
     */
    type?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuListResVo
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof MenuListResVo
     */
    permission?: string;
    /**
     * 
     * @type {number}
     * @memberof MenuListResVo
     */
    sort?: number;
    /**
     * 
     * @type {number}
     * @memberof MenuListResVo
     */
    parentId?: number;
    /**
     * 
     * @type {string}
     * @memberof MenuListResVo
     */
    remark?: string;
    /**
     * 
     * @type {Array<MenuListResVo>}
     * @memberof MenuListResVo
     */
    children?: Array<MenuListResVo>;
}


