// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { MenuAllResVo } from './menu-all-res-vo';

/**
 * 
 * @export
 * @interface ResponseMenuAllResVo
 */
export interface ResponseMenuAllResVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseMenuAllResVo
     */
    code?: number;
    /**
     * 
     * @type {MenuAllResVo}
     * @memberof ResponseMenuAllResVo
     */
    data?: MenuAllResVo;
    /**
     * 
     * @type {string}
     * @memberof ResponseMenuAllResVo
     */
    msg?: string;
}


