// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { RoleAllResVo } from './role-all-res-vo';

/**
 * 
 * @export
 * @interface ResponseRoleAllResVo
 */
export interface ResponseRoleAllResVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseRoleAllResVo
     */
    code?: number;
    /**
     * 
     * @type {RoleAllResVo}
     * @memberof ResponseRoleAllResVo
     */
    data?: RoleAllResVo;
    /**
     * 
     * @type {string}
     * @memberof ResponseRoleAllResVo
     */
    msg?: string;
}


