// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { GetRoleByUserIdResVo } from './get-role-by-user-id-res-vo';

/**
 * 
 * @export
 * @interface ResponseGetRoleByUserIdResVo
 */
export interface ResponseGetRoleByUserIdResVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseGetRoleByUserIdResVo
     */
    code?: number;
    /**
     * 
     * @type {GetRoleByUserIdResVo}
     * @memberof ResponseGetRoleByUserIdResVo
     */
    data?: GetRoleByUserIdResVo;
    /**
     * 
     * @type {string}
     * @memberof ResponseGetRoleByUserIdResVo
     */
    msg?: string;
}


