// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DepartmentAllResVo } from './department-all-res-vo';

/**
 * 
 * @export
 * @interface ResponseDepartmentAllResVo
 */
export interface ResponseDepartmentAllResVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseDepartmentAllResVo
     */
    code?: number;
    /**
     * 
     * @type {DepartmentAllResVo}
     * @memberof ResponseDepartmentAllResVo
     */
    data?: DepartmentAllResVo;
    /**
     * 
     * @type {string}
     * @memberof ResponseDepartmentAllResVo
     */
    msg?: string;
}


