// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { DepartmentListResVo } from './department-list-res-vo';

/**
 * 
 * @export
 * @interface ResponseDepartmentListResVo
 */
export interface ResponseDepartmentListResVo {
    /**
     * 
     * @type {number}
     * @memberof ResponseDepartmentListResVo
     */
    code?: number;
    /**
     * 
     * @type {DepartmentListResVo}
     * @memberof ResponseDepartmentListResVo
     */
    data?: DepartmentListResVo;
    /**
     * 
     * @type {string}
     * @memberof ResponseDepartmentListResVo
     */
    msg?: string;
}


