// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleListVo
 */
export interface RoleListVo {
    /**
     * 
     * @type {number}
     * @memberof RoleListVo
     */
    page?: number;
    /**
     * 
     * @type {number}
     * @memberof RoleListVo
     */
    pageSize?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleListVo
     */
    name?: string;
}


