// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleAllResVo
 */
export interface RoleAllResVo {
    /**
     * 
     * @type {number}
     * @memberof RoleAllResVo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleAllResVo
     */
    name?: string;
    /**
     * 
     * @type {Array<RoleAllResVo>}
     * @memberof RoleAllResVo
     */
    children?: Array<RoleAllResVo>;
}


