// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleUpdateVo
 */
export interface RoleUpdateVo {
    /**
     * 
     * @type {number}
     * @memberof RoleUpdateVo
     */
    id?: number;
    /**
     * 
     * @type {number}
     * @memberof RoleUpdateVo
     */
    sort?: number;
    /**
     * 
     * @type {string}
     * @memberof RoleUpdateVo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleUpdateVo
     */
    permission?: string;
    /**
     * 
     * @type {string}
     * @memberof RoleUpdateVo
     */
    remark?: string;
    /**
     * 
     * @type {number}
     * @memberof RoleUpdateVo
     */
    parentId?: number;
    /**
     * 
     * @type {number}
     * @memberof RoleUpdateVo
     */
    isDelete?: number;
}


