// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserRoleUpdateVo
 */
export interface UserRoleUpdateVo {
    /**
     * 
     * @type {Array<number>}
     * @memberof UserRoleUpdateVo
     */
    roleIds?: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof UserRoleUpdateVo
     */
    userId?: number;
}


