// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserListResVo
 */
export interface UserListResVo {
    /**
     * 
     * @type {number}
     * @memberof UserListResVo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    account?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    mail?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    phone?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UserListResVo
     */
    createTime?: string;
}


