// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserAddVo
 */
export interface UserAddVo {
    /**
     * 
     * @type {string}
     * @memberof UserAddVo
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddVo
     */
    account: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddVo
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddVo
     */
    mail?: string;
    /**
     * 1正常 2 禁用
     * @type {string}
     * @memberof UserAddVo
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UserAddVo
     */
    phone?: string;
    /**
     * 部门id
     * @type {number}
     * @memberof UserAddVo
     */
    departmentId?: number;
}


