// tslint:disable
/**
 * admin
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserUpdateVo
 */
export interface UserUpdateVo {
    /**
     * 
     * @type {number}
     * @memberof UserUpdateVo
     */
    id?: number;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateVo
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateVo
     */
    mail?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateVo
     */
    status?: string;
    /**
     * 
     * @type {string}
     * @memberof UserUpdateVo
     */
    phone?: string;
    /**
     * 
     * @type {number}
     * @memberof UserUpdateVo
     */
    departmentId?: number;
}


